server:
  port: 18011

spring:
  application:
    name: jpa-h2
  datasource:
    # URL option example: https://www.baeldung.com/spring-boot-h2-database
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  # 数据库初始化: https://docs.spring.io/spring-boot/how-to/data-initialization.html
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # import.sql
      ddl-auto: create-drop
  # JDBC, R2DBC
  #  sql:
  #    init:
  #      mode: always
  #      schema-locations: optional:classpath*:schema.sql
  #      data-locations: optional:classpath*:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console