CPPFLAGS =
CFLAGS = -g -pthread
LDFLAGS = 

TARGET = threadid threads queue ptqueue

all: $(TARGET)

# use make defaule rules for single c source files
# $(TARGET): $(TARGET).c
# 	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ $^

clean:
	$(RM) $(TARGET)
