server:
  port: 18015

spring:
  application:
    name: eureka-instance

eureka:
  # see org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
  client:
    service-url:
      defaultZone: http://127.0.0.1:18014/eureka/
  # see org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

# # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.actuator
management:
  server.port: ${server.port}
  # 开启所有端点
  endpoints.web.exposure.include: "*"
  # 开启Actuator info端点
  info.env.enabled: true