server:
  port: 18021
  shutdown: graceful
  # Reactor Netty
  # see org.springframework.boot.autoconfigure.web.ServerProperties.Netty
  # see https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.server.server.netty.connection-timeout
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

logging:
  level:
    org.springframework.r2dbc: DEBUG

spring:
  application:
    name: webflux
  lifecycle:
    timeout-per-shutdown-phase: 15s
  # R2DBC配置
  # see https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.data.spring.r2dbc.generate-unique-name
  r2dbc:
    url: r2dbc:mysql://localhost:3306/devops
    username: root
    password: change_me
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

# 应用配置
app:
  webmvc-service-uri: http://localhost:18020