server:
  port: 19000
  # see BasicErrorController
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-path: always
    include-stacktrace: always
    path: /error
    whitelabel:
      enabled: true

logging:
  level:
    org.springframework.security: trace


spring:
  application:
    name: authorization-server
# see com.spike.springcloud.oauth2.authz.config.SecurityConfig
# more: https://docs.spring.io/spring-boot/appendix/application-properties/index.html
#  security:
#    user:
#      name: user
#      password: password
#    oauth2:
#      # 配置授权服务器: org.springframework.boot.autoconfigure.security.oauth2.server.servlet.OAuth2AuthorizationServerProperties
#      authorizationserver:
#        client:
#          oidc-client:
#            registration:
#              client-id: "oidc-client"
#              client-secret: "{noop}secret"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
#              post-logout-redirect-uris:
#                - "http://127.0.0.1:8080/"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true