server:
  port: 18002
  # see BasicErrorController
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-path: always
    include-stacktrace: always
    path: /error
    whitelabel:
      enabled: true

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: keycloak-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authz.com:19001/realms/myrealm/protocol/openid-connect/certs